import crypto from 'crypto';
import { serverWalletService } from './walletService.ts';

export type ReferralStatus='REGISTERED'|'QUALIFIED'|'COMPLETED'|'CANCELLED';
export interface ReferralRecord{id:string;referrerUserId:string;referredUserId:string;referralCode:string;status:ReferralStatus;createdAt:string;idempotencyKey:string;rewardAmount:number;rewardCredited:boolean;rewardCreditedAt?:string;}
export interface UserReferralProfile{userId:string;displayName:string;referralCode:string;referredByUserId:string|null;createdAt:string;}
export interface ReferralConfig{REFERRAL_REWARD_AMOUNT:number;REFERRAL_COMMISSION_RATE:number;IS_REWARD_ACTIVE:boolean;QUALIFYING_EVENT:'FIRST_DEPOSIT'|'FIRST_BET'|'MANUAL_ACTIVATION';}
export const DEFAULT_REFERRAL_CONFIG:ReferralConfig={REFERRAL_REWARD_AMOUNT:0,REFERRAL_COMMISSION_RATE:0,IS_REWARD_ACTIVE:false,QUALIFYING_EVENT:'FIRST_DEPOSIT'};
const CODE_CHARSET='23456789ABCDEFGHJKMNPQRSTUVWXYZ';
export class ServerReferralService{
 private config={...DEFAULT_REFERRAL_CONFIG}; private users=new Map<string,UserReferralProfile>(); private codeToUserId=new Map<string,string>(); private referralsByReferredUser=new Map<string,ReferralRecord>(); private referralsByReferrer=new Map<string,ReferralRecord[]>();
 constructor(){this.seedDefaultUsers();}
 private seedDefaultUsers(){for(const s of [{userId:'player-sumit',displayName:'Sumit Joshi',code:'WIN42SUM8'},{userId:'player-arjun',displayName:'Arjun Mehta',code:'WIN78ARJ1',referredBy:'player-sumit'},{userId:'player-sneha',displayName:'Sneha Roy',code:'WIN99SNE3'},{userId:'demo-player-uid-123',displayName:'Demo Player VIP',code:'WIN123DEM'}] as any[])this.registerSeedUser(s.userId,s.displayName,s.code,s.referredBy);}
 private registerSeedUser(userId:string,displayName:string,code:string,referredBy?:string){const c=code.toUpperCase();this.users.set(userId,{userId,displayName,referralCode:c,referredByUserId:referredBy||null,createdAt:new Date().toISOString()});this.codeToUserId.set(c,userId);if(referredBy){const r:ReferralRecord={id:`ref_rel_${userId}`,referrerUserId:referredBy,referredUserId:userId,referralCode:c,status:'REGISTERED',createdAt:new Date().toISOString(),idempotencyKey:`rel_${userId}_${referredBy}`,rewardAmount:0,rewardCredited:false};this.referralsByReferredUser.set(userId,r);this.referralsByReferrer.set(referredBy,[...(this.referralsByReferrer.get(referredBy)||[]),r]);}}
 public generateUniqueReferralCode(){for(let a=0;a<100;a++){let c='WIN';const b=crypto.randomBytes(6);for(let i=0;i<6;i++)c+=CODE_CHARSET[b[i]%CODE_CHARSET.length];if(!this.codeToUserId.has(c))return c;}throw new Error('Unable to allocate referral code.');}
 public resolveReferralCode(code:string){if(!code||typeof code!=='string')return{valid:false,error:'Referral code is required.'};const c=code.trim().toUpperCase(),id=this.codeToUserId.get(c);if(!id)return{valid:false,error:'Invalid referral code.'};return{valid:true,referrerDisplayName:this.users.get(id)?.displayName||'WINORA Player',referralCode:c};}
 public registerUser(p:{userId:string;displayName:string;referralCodeToRedeem?:string}){let u=this.users.get(p.userId);if(!u){const code=this.generateUniqueReferralCode();u={userId:p.userId,displayName:p.displayName||'WINORA Player',referralCode:code,referredByUserId:null,createdAt:new Date().toISOString()};this.users.set(p.userId,u);this.codeToUserId.set(code,p.userId);}if(p.referralCodeToRedeem){const r=this.createReferralRelationship({referredUserId:p.userId,referralCode:p.referralCodeToRedeem});if(!r.success)return{success:false,userProfile:u,error:r.error,errorCode:r.errorCode};return{success:true,userProfile:u,referralRecord:r.referralRecord};}return{success:true,userProfile:u};}
 public createReferralRelationship(p:{referredUserId:string;referralCode:string}){if(!p.referredUserId)return{success:false,error:'User ID is required.',errorCode:'INVALID_USER_ID'};const c=p.referralCode?.trim().toUpperCase();const ref=this.codeToUserId.get(c);if(!ref)return{success:false,error:'Invalid referral code.',errorCode:'INVALID_REFERRAL_CODE'};if(ref===p.referredUserId)return{success:false,error:'Self-referral is forbidden.',errorCode:'SELF_REFERRAL_FORBIDDEN'};const user=this.users.get(p.referredUserId),existing=this.referralsByReferredUser.get(p.referredUserId);const current=user?.referredByUserId||existing?.referrerUserId;if(current){if(current===ref)return{success:true,referralRecord:existing};return{success:false,error:'User already has an established referrer.',errorCode:'REFERRER_ALREADY_ATTACHED'};}let cur:string|null=ref;const seen=new Set<string>();while(cur){if(cur===p.referredUserId)return{success:false,error:'Referral loop detected.',errorCode:'REFERRAL_LOOP_DETECTED'};if(seen.has(cur))break;seen.add(cur);cur=this.users.get(cur)?.referredByUserId||null;}
 const now=new Date().toISOString();const record:ReferralRecord={id:`ref_rel_${p.referredUserId}`,referrerUserId:ref,referredUserId:p.referredUserId,referralCode:c,status:'REGISTERED',createdAt:now,idempotencyKey:`rel_${p.referredUserId}_${ref}`,rewardAmount:0,rewardCredited:false};if(user)user.referredByUserId=ref;else{const code=this.generateUniqueReferralCode();this.users.set(p.referredUserId,{userId:p.referredUserId,displayName:'WINORA Player',referralCode:code,referredByUserId:ref,createdAt:now});this.codeToUserId.set(code,p.referredUserId);}this.referralsByReferredUser.set(p.referredUserId,record);this.referralsByReferrer.set(ref,[...(this.referralsByReferrer.get(ref)||[]),record]);return{success:true,referralRecord:record};}
 public async processReferralReward(p:{referredUserId:string;event:'FIRST_DEPOSIT'|'FIRST_BET'|'MANUAL_ACTIVATION';idempotencyKey?:string}){const r=this.referralsByReferredUser.get(p.referredUserId);if(!r)return{success:false,rewarded:false,reason:'NO_REFERRER_RELATIONSHIP',message:'User does not have an established referral relationship.'};if(!this.config.IS_REWARD_ACTIVE||this.config.REFERRAL_REWARD_AMOUNT<=0)return{success:false,rewarded:false,reason:'REWARD_CONDITIONS_NOT_MET',message:'Referral reward is not activated.'};if(this.config.QUALIFYING_EVENT!==p.event)return{success:false,rewarded:false,reason:'EVENT_MISMATCH',message:`Event ${p.event} does not match configured qualifying event ${this.config.QUALIFYING_EVENT}.`};if(r.rewardCredited)return{success:true,rewarded:false,reason:'ALREADY_PROCESSED',message:'Referral reward has already been processed.',rewardAmount:r.rewardAmount,creditedWallet:'main' as const};const amount=this.config.REFERRAL_REWARD_AMOUNT;await serverWalletService.creditReferralReward({referralKey:p.idempotencyKey||`ref_reward_${p.referredUserId}_${p.event}`,userId:p.referredUserId,amount,referrerId:r.referrerUserId});r.rewardAmount=amount;r.rewardCredited=true;r.rewardCreditedAt=new Date().toISOString();r.status='COMPLETED';return{success:true,rewarded:true,message:`Referral reward of ₹${amount} demo credits successfully credited to Main Wallet.`,rewardAmount:amount,creditedWallet:'main' as const};}
 public getUserProfile(id:string){return this.users.get(id);} public getReferralRecordByReferred(id:string){return this.referralsByReferredUser.get(id);} public getReferralsByReferrer(id:string){return this.referralsByReferrer.get(id)||[];} public getConfig(){return{...this.config};}
 public updateConfigForTesting(u:Partial<ReferralConfig>){this.config={...this.config,...u};}
 public resetForTesting(){this.config={...DEFAULT_REFERRAL_CONFIG};this.users.clear();this.codeToUserId.clear();this.referralsByReferredUser.clear();this.referralsByReferrer.clear();this.seedDefaultUsers();}
}
export const serverReferralService=new ServerReferralService();
