import crypto from 'crypto';
import { serverGameEntryService, ServerGameRound, ServerGameEntry, SERVER_GAMES_CONFIG } from './gameEntryService.ts';

export interface GameResultRecord { resultId:string; gameId:string; roundId:string; roundNumber:number; gameName:string; winningNumber:string; resultColor:'GREEN'|'RED'; declaredBy:string; declaredAt:string; ruleVersion:string; status:'PROCESSING'|'COMPLETED'|'FAILED'; settlementId:string; createdAt:string; summary?:SettlementSummary; }
export interface SettlementSummary { settlementId:string; resultId:string; roundId:string; gameId:string; winningNumber:string; resultColor:'GREEN'|'RED'; totalEntries:number; winningEntries:number; losingEntries:number; totalStake:number; total90xRewards:number; totalProtectionRefund:number; totalDemoRewards:number; failedSettlements:number; settlementTimestamp:string; winningEntryIds:string[]; }
export interface WalletRewardTransaction { transactionId:string; userId:string; entryId:string; resultId:string; roundId:string; rewardType:'GAME_WIN'|'HOURLY_PROTECTION_REFUND'|'90x_win'|'protection_refund'|'90x_win_protection_refund'; amount:number; createdAt:string; }
export interface SettlementAuditLog { auditId:string; event:'RESULT_DECLARED'|'REWARD_SETTLED'|'SETTLEMENT_FAILED'; actor:string; roundId:string; resultId:string; settlementId:string; entryReference?:string; details?:Record<string,unknown>; timestamp:string; }

class ResultSettlementService {
 private results=new Map<string,GameResultRecord>(); private resultsByRound=new Map<string,GameResultRecord>(); private walletRewardLedger:WalletRewardTransaction[]=[]; private auditLogs:SettlementAuditLog[]=[];
 private completedSettlementIds=new Set<string>();
 constructor(){this.seedSampleResults();}
 private seedSampleResults(){const t=new Date(Date.now()-3600000).toISOString();const summary:SettlementSummary={settlementId:'SETTLE-INIT-9001',resultId:'RES-GX100-42-G',roundId:'round-gx-100',gameId:'game_x',winningNumber:'42',resultColor:'GREEN',totalEntries:18,winningEntries:2,losingEntries:16,totalStake:3600,total90xRewards:18000,totalProtectionRefund:0,totalDemoRewards:18000,failedSettlements:0,settlementTimestamp:t,winningEntryIds:['ENTRY-SEED-01','ENTRY-SEED-02']};const record:GameResultRecord={resultId:'RES-GX100-42-G',gameId:'game_x',roundId:'round-gx-100',roundNumber:100,gameName:'Game X',winningNumber:'42',resultColor:'GREEN',declaredBy:'master-admin',declaredAt:t,ruleVersion:'1.0',status:'COMPLETED',settlementId:'SETTLE-INIT-9001',createdAt:t,summary};this.results.set(record.resultId,record);this.resultsByRound.set(record.roundId,record);this.completedSettlementIds.add(record.settlementId);}
 private logAudit(entry:Omit<SettlementAuditLog,'auditId'|'timestamp'>){this.auditLogs.unshift({...entry,auditId:`AUD-${Date.now()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`,timestamp:new Date().toISOString()});}
 public getAuditLogs(){return this.auditLogs;} public getRecentResults(){return Array.from(this.results.values()).sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());} public getResultByRoundId(roundId:string){return this.resultsByRound.get(roundId);} public getRewardLedger(){return this.walletRewardLedger;}
 public calculateSettlementLiability(p:{gameId:string;roundId:string;winningNumber:string;resultColor:'GREEN'|'RED'}){const game=SERVER_GAMES_CONFIG.find(g=>g.id===p.gameId);const entries=serverGameEntryService.getEntriesForRound(p.roundId);const hourly=p.gameId==='hourly_dhamaka'||Boolean(game?.hasGreenRefund);let totalStake=0,total90xPayout=0,totalProtectionRefund=0,winningBidsCount=0,matchingColorBidsCount=0;for(const e of entries){totalStake+=e.totalStake;for(const s of e.selections){if(s.number===p.winningNumber){total90xPayout+=s.stake*(game?.payoutMultiplier||90);winningBidsCount++;}if(hourly&&s.color===p.resultColor){totalProtectionRefund+=Number((s.stake*.8).toFixed(2));matchingColorBidsCount++;}}}totalProtectionRefund=Number(totalProtectionRefund.toFixed(2));const totalLiability=Number((total90xPayout+totalProtectionRefund).toFixed(2));return{winningNumber:p.winningNumber,resultColor:p.resultColor,totalEntries:entries.length,totalStake,total90xPayout,totalProtectionRefund,totalLiability,netHousePnL:Number((totalStake-totalLiability).toFixed(2)),winningBidsCount,matchingColorBidsCount};}
 public freezeRound(p:{actorRole:string;actorId:string;gameId:string;roundId:string}){if(p.actorRole!=='master'&&p.actorRole!=='admin')return{success:false,errorCode:'UNAUTHORIZED',error:'Access denied.'};const r=serverGameEntryService.getRound(p.gameId);if(!r||r.id!==p.roundId)return{success:false,errorCode:'INVALID_ROUND',error:`Round ${p.roundId} not found.`};if(r.status==='COMPLETED')return{success:false,errorCode:'ROUND_ALREADY_COMPLETED',error:'Round has already been completed.'};r.status='FROZEN';return{success:true,round:r};}
 public async declareResultAndSettle(p:{actorRole:string;actorId:string;gameId:string;roundId:string;winningNumber:string;resultColor:'GREEN'|'RED';idempotencyKey?:string}){if(p.actorRole!=='master'&&p.actorRole!=='admin')return{success:false,errorCode:'UNAUTHORIZED',error:'Access denied.'};const game=SERVER_GAMES_CONFIG.find(g=>g.id===p.gameId);if(!game)return{success:false,errorCode:'INVALID_GAME',error:'Invalid game.'};const existing=this.resultsByRound.get(p.roundId);if(existing?.status==='COMPLETED')return{success:false,errorCode:'ROUND_ALREADY_SETTLED',error:'Round has already been settled.',result:existing,summary:existing.summary};const round=serverGameEntryService.getRound(p.gameId);if(!round||round.id!==p.roundId)return{success:false,errorCode:'INVALID_ROUND',error:'Invalid round.'};if(round.status==='OPEN'&&Date.now()>=new Date(round.freezeTime).getTime())round.status='FROZEN';if(round.status!=='FROZEN')return{success:false,errorCode:`ROUND_${round.status}`,error:'Only a FROZEN round may be settled.'};if(!/^\d{2}$/.test(p.winningNumber)||Number(p.winningNumber)>99)return{success:false,errorCode:'INVALID_WINNING_NUMBER',error:'Winning number must be 00–99.'};if(p.resultColor!=='GREEN'&&p.resultColor!=='RED')return{success:false,errorCode:'INVALID_RESULT_COLOR',error:'Result color must be GREEN or RED.'};round.status='PROCESSING';const settlementId=p.idempotencyKey?`SETTLE-${crypto.createHash('sha256').update(`${p.roundId}:${p.idempotencyKey}`).digest('hex').slice(0,16).toUpperCase()}`:`SETTLE-${crypto.randomBytes(8).toString('hex').toUpperCase()}`;const resultId=`RES-${game.code.replace(/[^a-zA-Z0-9]/g,'')}-${round.roundNumber}-${p.winningNumber}-${p.resultColor[0]}`;const declaredAt=new Date().toISOString();if(this.completedSettlementIds.has(settlementId))return{success:false,errorCode:'DOUBLE_SETTLEMENT_ATTEMPT',error:'Duplicate settlement rejected.'};this.logAudit({event:'RESULT_DECLARED',actor:p.actorId,roundId:p.roundId,resultId,settlementId,details:{gameId:p.gameId,winningNumber:p.winningNumber,resultColor:p.resultColor}});
 try{const entries=serverGameEntryService.getEntriesForRound(p.roundId);let totalStake=0,total90xRewards=0,totalProtectionRefund=0,totalDemoRewards=0,winningCount=0,losingCount=0;const winningEntryIds:string[]=[];const hourly=p.gameId==='hourly_dhamaka'||Boolean(game.hasGreenRefund);
  for(const entry of entries){totalStake+=entry.totalStake;let base=0,refund=0;for(const s of entry.selections){if(s.number===p.winningNumber)base+=s.stake*game.payoutMultiplier;if(hourly&&s.color===p.resultColor)refund+=Number((s.stake*.8).toFixed(2));}refund=Number(refund.toFixed(2));const credit=Number((base+refund).toFixed(2));total90xRewards+=base;totalProtectionRefund=Number((totalProtectionRefund+refund).toFixed(2));totalDemoRewards=Number((totalDemoRewards+credit).toFixed(2));if(credit>0){winningCount++;winningEntryIds.push(entry.id);await serverGameEntryService.creditUserDemoReward(entry.userId,credit,settlementId,entry.id);serverGameEntryService.updateEntry(entry.id,{status:'WON',settledReward:base,protectionRefund:refund,totalSettlementCredit:credit,settledWinningNumber:p.winningNumber,settledResultColor:p.resultColor,settlementId,settledAt:declaredAt});if(base>0)this.walletRewardLedger.push({transactionId:`TX-WIN-${settlementId}-${entry.id}`,userId:entry.userId,entryId:entry.id,resultId,roundId:p.roundId,rewardType:'GAME_WIN',amount:base,createdAt:declaredAt});if(refund>0)this.walletRewardLedger.push({transactionId:`TX-PROT-${settlementId}-${entry.id}`,userId:entry.userId,entryId:entry.id,resultId,roundId:p.roundId,rewardType:'HOURLY_PROTECTION_REFUND',amount:refund,createdAt:declaredAt});this.logAudit({event:'REWARD_SETTLED',actor:'system_settlement_engine',roundId:p.roundId,resultId,settlementId,entryReference:entry.id,details:{userId:entry.userId,base90x:base,protectionRefund:refund,totalCredited:credit}});}else{losingCount++;serverGameEntryService.updateEntry(entry.id,{status:'LOST',settledReward:0,protectionRefund:0,totalSettlementCredit:0,settledWinningNumber:p.winningNumber,settledResultColor:p.resultColor,settlementId,settledAt:declaredAt});}}
  const summary:SettlementSummary={settlementId,resultId,roundId:p.roundId,gameId:p.gameId,winningNumber:p.winningNumber,resultColor:p.resultColor,totalEntries:entries.length,winningEntries:winningCount,losingEntries:losingCount,totalStake,total90xRewards,totalProtectionRefund,totalDemoRewards,failedSettlements:0,settlementTimestamp:declaredAt,winningEntryIds};round.status='COMPLETED';round.resultNumber=p.winningNumber;round.resultColor=p.resultColor;const result:GameResultRecord={resultId,gameId:p.gameId,roundId:p.roundId,roundNumber:round.roundNumber,gameName:game.name,winningNumber:p.winningNumber,resultColor:p.resultColor,declaredBy:p.actorId,declaredAt,ruleVersion:'2.0',status:'COMPLETED',settlementId,createdAt:declaredAt,summary};this.results.set(resultId,result);this.resultsByRound.set(p.roundId,result);this.completedSettlementIds.add(settlementId);serverGameEntryService.spawnNextRound(p.gameId);return{success:true,result,summary};
 }catch(e:any){round.status='PROCESSING';this.logAudit({event:'SETTLEMENT_FAILED',actor:'system_settlement_engine',roundId:p.roundId,resultId,settlementId,details:{error:e?.message||String(e)}});return{success:false,errorCode:'SETTLEMENT_EXECUTION_FAILED',error:`Settlement failed: ${e?.message||String(e)}`};}}
}
export const serverResultSettlementService=new ResultSettlementService();
