import crypto from 'crypto';
import { adminDb } from './firebaseAdmin.ts';
import { getPaymentProvider, PaymentGatewayProvider } from './paymentProvider.ts';

export type KycStatus='not_submitted'|'pending'|'verified'|'rejected';
export type AccountVerificationStatus='unverified'|'verified'|'restricted';
export type TransactionType='deposit'|'withdrawal'|'game_debit'|'game_reward'|'referral_reward';
export type TransactionStatus='pending'|'completed'|'failed'|'cancelled';
export type AuditOperation='deposit_credit'|'withdrawal_hold'|'withdrawal_debit'|'withdrawal_release_failed'|'game_debit'|'game_reward'|'referral_reward';
export interface WalletRecord{uid:string;currency:string;balance:number;heldBalance:number;kycStatus:KycStatus;withdrawalEligibility:boolean;accountVerificationStatus:AccountVerificationStatus;createdAt:string;updatedAt:string;}
export interface TransactionRecord{transactionId:string;uid:string;type:TransactionType;amount:number;currency:string;status:TransactionStatus;paymentMethod:string;providerReference:string;idempotencyKey:string;destinationAccount?:string;failureReason?:string;auditReference?:string;clientIp?:string;userAgent?:string;createdAt:string;updatedAt:string;}
export interface AuditRecord{auditId:string;uid:string;transactionId:string;operation:AuditOperation;amount:number;previousBalance:number;newBalance:number;timestamp:string;sourceReference:string;}
const walletRef=(uid:string)=>adminDb.collection('wallets').doc(uid);
const txRef=(id:string)=>adminDb.collection('transactions').doc(id);
const auditRef=(id:string)=>adminDb.collection('wallet_audits').doc(id);
const idempotencyRef=(key:string)=>adminDb.collection('wallet_idempotency').doc(crypto.createHash('sha256').update(key).digest('hex'));
class ServerWalletService{
 private paymentProvider:PaymentGatewayProvider; constructor(){this.paymentProvider=getPaymentProvider();}
 private newWallet(uid:string,currency='INR'):WalletRecord{const now=new Date().toISOString();return{uid,currency,balance:5000,heldBalance:0,kycStatus:'verified',withdrawalEligibility:true,accountVerificationStatus:'verified',createdAt:now,updatedAt:now};}
 public async getOrCreateWallet(uid:string,currency='INR'):Promise<WalletRecord>{if(!uid)throw new Error('Authentication required.');const ref=walletRef(uid);return adminDb.runTransaction(async t=>{const snap=await t.get(ref);if(snap.exists)return snap.data() as WalletRecord;const wallet=this.newWallet(uid,currency);t.create(ref,wallet);return wallet;});}
 public async getWallet(uid:string){const wallet=await this.getOrCreateWallet(uid);return{...wallet,availableBalance:Math.max(0,wallet.balance-wallet.heldBalance)};}
 public async debitForGame(p:{uid:string;amount:number;idempotencyKey:string;gameId:string;roundId:string}):Promise<{wallet:WalletRecord;transactionId:string;duplicate:boolean}>{const{uid,amount,idempotencyKey,gameId,roundId}=p;if(!uid||!Number.isFinite(amount)||amount<=0)throw new Error('Invalid wallet debit.');if(!idempotencyKey)throw new Error('Idempotency key is required.');const idem=idempotencyRef(`game:${uid}:${idempotencyKey}`),wallet=walletRef(uid),transactionId=`TX-GAME-${crypto.randomBytes(8).toString('hex').toUpperCase()}`,tx=txRef(transactionId),auditId=`AUD-${crypto.randomBytes(8).toString('hex').toUpperCase()}`,audit=auditRef(auditId),now=new Date().toISOString();return adminDb.runTransaction(async t=>{const idemSnap=await t.get(idem);if(idemSnap.exists){const prior=idemSnap.data() as{transactionId:string};const priorWallet=await t.get(wallet);return{wallet:priorWallet.data() as WalletRecord,transactionId:prior.transactionId,duplicate:true};}const walletSnap=await t.get(wallet);const current=walletSnap.exists?walletSnap.data() as WalletRecord:this.newWallet(uid);const available=current.balance-current.heldBalance;if(available<amount)throw new Error(`Insufficient demo credits in Main Wallet. Required: ₹${amount.toLocaleString()}, Available: ₹${available.toLocaleString()}.`);const updated={...current,balance:Number((current.balance-amount).toFixed(2)),updatedAt:now};const record:TransactionRecord={transactionId,uid,type:'game_debit',amount,currency:current.currency,status:'completed',paymentMethod:'Main Wallet',providerReference:`${gameId}:${roundId}`,idempotencyKey,createdAt:now,updatedAt:now};const ar:AuditRecord={auditId,uid,transactionId,operation:'game_debit',amount,previousBalance:current.balance,newBalance:updated.balance,timestamp:now,sourceReference:`game:${gameId}:${roundId}`};t.set(wallet,updated,{merge:true});t.create(tx,record);t.create(audit,ar);t.create(idem,{transactionId,uid,createdAt:now,operation:'game_debit'});return{wallet:updated,transactionId,duplicate:false};});}
 public async creditGameReward(p:{uid:string;amount:number;idempotencyKey:string;sourceReference:string}):Promise<{wallet:WalletRecord;transactionId:string;duplicate:boolean}>{const{uid,amount,idempotencyKey,sourceReference}=p;if(!uid||!Number.isFinite(amount)||amount<=0)throw new Error('Invalid wallet credit.');if(!idempotencyKey)throw new Error('Idempotency key is required.');const idem=idempotencyRef(`reward:${uid}:${idempotencyKey}`),wallet=walletRef(uid),transactionId=`TX-REWARD-${crypto.randomBytes(8).toString('hex').toUpperCase()}`,tx=txRef(transactionId),auditId=`AUD-${crypto.randomBytes(8).toString('hex').toUpperCase()}`,audit=auditRef(auditId),now=new Date().toISOString();return adminDb.runTransaction(async t=>{const idemSnap=await t.get(idem);if(idemSnap.exists){const prior=idemSnap.data() as{transactionId:string};const priorWallet=await t.get(wallet);return{wallet:priorWallet.data() as WalletRecord,transactionId:prior.transactionId,duplicate:true};}const walletSnap=await t.get(wallet);const current=walletSnap.exists?walletSnap.data() as WalletRecord:this.newWallet(uid);const updated={...current,balance:Number((current.balance+amount).toFixed(2)),updatedAt:now};const record:TransactionRecord={transactionId,uid,type:'game_reward',amount,currency:current.currency,status:'completed',paymentMethod:'Main Wallet',providerReference:sourceReference,idempotencyKey,createdAt:now,updatedAt:now};const ar:AuditRecord={auditId,uid,transactionId,operation:'game_reward',amount,previousBalance:current.balance,newBalance:updated.balance,timestamp:now,sourceReference};t.set(wallet,updated,{merge:true});t.create(tx,record);t.create(audit,ar);t.create(idem,{transactionId,uid,createdAt:now,operation:'game_reward'});return{wallet:updated,transactionId,duplicate:false};});}
 public async creditReferralReward(p:{referralKey:string;userId:string;amount:number;referrerId?:string}){if(!Number.isFinite(p.amount)||p.amount<=0)throw new Error('Invalid referral reward amount.');const first=await this.creditGameReward({uid:p.userId,amount:p.amount,idempotencyKey:`referral:${p.referralKey}:referred`,sourceReference:`referral:${p.referralKey}`});let final=first.wallet;if(p.referrerId){const second=await this.creditGameReward({uid:p.referrerId,amount:p.amount,idempotencyKey:`referral:${p.referralKey}:referrer`,sourceReference:`referral:${p.referralKey}`});final=second.wallet;}return{success:!first.duplicate,message:first.duplicate?'This referral reward has already been credited.':`Referral reward credited to Main Wallet (Key: ${p.referralKey}).`,remainingBalance:{main:final.balance}};}
 public async getUserTransactions(uid:string){const snap=await adminDb.collection('transactions').where('uid','==',uid).orderBy('createdAt','desc').limit(200).get();return snap.docs.map(d=>d.data() as TransactionRecord);}
 public async getUserAudits(uid:string){const snap=await adminDb.collection('wallet_audits').where('uid','==',uid).orderBy('timestamp','desc').limit(200).get();return snap.docs.map(d=>d.data() as AuditRecord);}
 public async initiateDeposit(_p:any){throw new Error('VIRTUAL_ONLY');} public async requestWithdrawal(_p:any){throw new Error('VIRTUAL_ONLY');} public async handleWithdrawalSettlement(_r:string,_s:'completed'|'failed',_f?:string){throw new Error('VIRTUAL_ONLY');} public async handlePaymentWebhook(_b:string,_s:string){throw new Error('VIRTUAL_ONLY');} public async simulateSandboxWebhook(_t:string,_a:'confirm_payment'|'decline_payment'|'confirm_payout'|'decline_payout'){throw new Error(process.env.NODE_ENV==='production'?'NOT_FOUND':'VIRTUAL_ONLY');}
}
export const serverWalletService=new ServerWalletService();
